/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rms;

/**
 *
 * @author Leemon
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        customerButton = new javax.swing.JButton();
        serialButton = new javax.swing.JButton();
        stuffButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        customerLabel = new javax.swing.JLabel();
        customerLabel1 = new javax.swing.JLabel();
        customerLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Mangement System");
        setBackground(new java.awt.Color(0, 204, 255));
        setFont(new java.awt.Font("Adobe Arabic", 1, 10)); // NOI18N

        heading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/img/Untitled-1.png"))); // NOI18N
        heading.setText(" ");

        customerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/img/updated customer.png"))); // NOI18N
        customerButton.setText(" ");
        customerButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                customerButtonMouseDragged(evt);
            }
        });
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });

        serialButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/img/updated serial.png"))); // NOI18N
        serialButton.setText(" ");
        serialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialButtonActionPerformed(evt);
            }
        });

        stuffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/img/updared stuff.png"))); // NOI18N
        stuffButton.setText(" ");
        stuffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuffButtonActionPerformed(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/img/exit.png"))); // NOI18N
        exitButton.setText(" ");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        customerLabel.setBackground(new java.awt.Color(255, 255, 255));
        customerLabel.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(0, 0, 0));
        customerLabel.setText("Customer");

        customerLabel1.setBackground(new java.awt.Color(255, 255, 255));
        customerLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        customerLabel1.setForeground(new java.awt.Color(0, 0, 0));
        customerLabel1.setText("Management");

        customerLabel2.setBackground(new java.awt.Color(255, 255, 255));
        customerLabel2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        customerLabel2.setForeground(new java.awt.Color(0, 0, 0));
        customerLabel2.setText("Serial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(customerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(customerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(serialButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(stuffButton)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(customerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(exitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerLabel)
                    .addComponent(customerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerButton)
                    .addComponent(serialButton)
                    .addComponent(stuffButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
            System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });  
  this.setVisible(false);
        //this.dispose();
      
    }//GEN-LAST:event_customerButtonActionPerformed

    private void stuffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuffButtonActionPerformed
        Stuff f=new Stuff();
        f.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_stuffButtonActionPerformed

    private void serialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialButtonActionPerformed
         Serial s= new Serial();
         this.setVisible(false);
         s.setVisible(true);
         
    }//GEN-LAST:event_serialButtonActionPerformed

    private void customerButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerButtonMouseDragged
                     // TODO add your handling code here:
    }//GEN-LAST:event_customerButtonMouseDragged

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerButton;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customerLabel1;
    private javax.swing.JLabel customerLabel2;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel heading;
    private javax.swing.JButton serialButton;
    private javax.swing.JButton stuffButton;
    // End of variables declaration//GEN-END:variables
}
