/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rms;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leemon
 */
public class Serial extends javax.swing.JFrame {

    /**
     * Creates new form Serial
     */
    public Serial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        serialTable = new javax.swing.JTable();
        homeButton = new javax.swing.JButton();
        homeLabel = new javax.swing.JLabel();
        seeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serialTable.setBackground(new java.awt.Color(0, 204, 255));
        serialTable.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        serialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Sl No", "Date", "Time", "Table No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(serialTable);
        if (serialTable.getColumnModel().getColumnCount() > 0) {
            serialTable.getColumnModel().getColumn(0).setResizable(false);
            serialTable.getColumnModel().getColumn(1).setResizable(false);
            serialTable.getColumnModel().getColumn(2).setResizable(false);
            serialTable.getColumnModel().getColumn(3).setResizable(false);
            serialTable.getColumnModel().getColumn(4).setResizable(false);
        }

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/img/rounded_blue_home_button_4805.jpg"))); // NOI18N
        homeButton.setText(" ");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        homeLabel.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(204, 0, 0));
        homeLabel.setText(" Home");

        seeButton.setBackground(new java.awt.Color(0, 204, 0));
        seeButton.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        seeButton.setText("Click to see");
        seeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(homeLabel)
                .addGap(33, 33, 33)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(seeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        HomePage h= new HomePage();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void seeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeButtonActionPerformed
      seeButton.setBackground(Color.red);
        DefaultTableModel model= (DefaultTableModel)serialTable.getModel();
        try
        {
             BufferedReader wr = new BufferedReader( new FileReader("C:\\Users\\Leemon\\Documents\\NetBeansProjects\\RMS\\serial.txt"));
             String s;
             int count=0;
             while( (s=wr.readLine())!=null)
             {
                 String []l= s.split(" ");
                 String c= String.valueOf(++count);
                  
                 model.addRow(new Object[]{l[0],c,l[1],l[2],l[3]});
                 
             }
            
            
        }
        catch(Exception e)
        {
            System.out.println( "cant find file");
        }
        
       
       
    }//GEN-LAST:event_seeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton seeButton;
    private javax.swing.JTable serialTable;
    // End of variables declaration//GEN-END:variables
}
