/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rms;
 
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Leemon
 */
public  class Stuff extends javax.swing.JFrame  {

    /**
     * Creates new form Stuff
     */
    public Stuff() {
        initComponents();
        afterLogin.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        afterLogin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        managementTable = new javax.swing.JTable();
        serialCleanButton = new javax.swing.JButton();
        orderCleanButton = new javax.swing.JButton();
        seeOrderList = new javax.swing.JButton();
        wholeInfoButton = new javax.swing.JButton();
        stuffLoginPanel = new javax.swing.JPanel();
        stuffLebel1 = new javax.swing.JLabel();
        stuffLebel2 = new javax.swing.JLabel();
        stuffLebel3 = new javax.swing.JLabel();
        loginLable1 = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        buttonN = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Management System( Stuff )");
        setBackground(new java.awt.Color(0, 204, 255));
        setMinimumSize(new java.awt.Dimension(1000, 1000));

        afterLogin.setBackground(new java.awt.Color(0, 255, 255));

        managementTable.setBackground(new java.awt.Color(51, 102, 255));
        managementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table No", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(managementTable);
        if (managementTable.getColumnModel().getColumnCount() > 0) {
            managementTable.getColumnModel().getColumn(0).setResizable(false);
            managementTable.getColumnModel().getColumn(1).setResizable(false);
            managementTable.getColumnModel().getColumn(2).setResizable(false);
            managementTable.getColumnModel().getColumn(3).setResizable(false);
            managementTable.getColumnModel().getColumn(4).setResizable(false);
            managementTable.getColumnModel().getColumn(5).setResizable(false);
            managementTable.getColumnModel().getColumn(6).setResizable(false);
            managementTable.getColumnModel().getColumn(7).setResizable(false);
            managementTable.getColumnModel().getColumn(8).setResizable(false);
            managementTable.getColumnModel().getColumn(9).setResizable(false);
        }

        serialCleanButton.setBackground(new java.awt.Color(51, 204, 0));
        serialCleanButton.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        serialCleanButton.setText("click to clean(Serial)");
        serialCleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialCleanButtonActionPerformed(evt);
            }
        });

        orderCleanButton.setBackground(new java.awt.Color(51, 204, 0));
        orderCleanButton.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        orderCleanButton.setText("click to clean(OrderList)");
        orderCleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCleanButtonActionPerformed(evt);
            }
        });

        seeOrderList.setBackground(new java.awt.Color(0, 204, 0));
        seeOrderList.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        seeOrderList.setText("Click to see(Order)");
        seeOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeOrderListActionPerformed(evt);
            }
        });

        wholeInfoButton.setBackground(new java.awt.Color(0, 204, 0));
        wholeInfoButton.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        wholeInfoButton.setText("Whole Info");
        wholeInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wholeInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout afterLoginLayout = new javax.swing.GroupLayout(afterLogin);
        afterLogin.setLayout(afterLoginLayout);
        afterLoginLayout.setHorizontalGroup(
            afterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
            .addGroup(afterLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serialCleanButton)
                .addGap(18, 18, 18)
                .addComponent(orderCleanButton)
                .addGap(18, 18, 18)
                .addComponent(seeOrderList)
                .addGap(18, 18, 18)
                .addComponent(wholeInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        afterLoginLayout.setVerticalGroup(
            afterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afterLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(afterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialCleanButton)
                    .addComponent(orderCleanButton)
                    .addComponent(seeOrderList)
                    .addComponent(wholeInfoButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        stuffLoginPanel.setBackground(new java.awt.Color(50, 229, 229));

        stuffLebel1.setBackground(new java.awt.Color(255, 0, 0));
        stuffLebel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        stuffLebel1.setForeground(java.awt.Color.red);
        stuffLebel1.setText(" User Name");

        stuffLebel2.setBackground(new java.awt.Color(255, 0, 0));
        stuffLebel2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        stuffLebel2.setForeground(java.awt.Color.red);
        stuffLebel2.setText("Password");

        stuffLebel3.setBackground(new java.awt.Color(255, 0, 0));
        stuffLebel3.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        stuffLebel3.setForeground(java.awt.Color.red);
        stuffLebel3.setText("Log In(Office Stuff)");

        loginLable1.setBackground(new java.awt.Color(255, 0, 0));
        loginLable1.setText(" ");

        logInButton.setBackground(new java.awt.Color(255, 0, 0));
        logInButton.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        logInButton.setForeground(new java.awt.Color(204, 204, 255));
        logInButton.setText(" Log In");
        logInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logInButtonMouseClicked(evt);
            }
        });
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/img/rounded_blue_home_button_4805.jpg"))); // NOI18N
        homeButton.setText(" ");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText(" Home");

        javax.swing.GroupLayout stuffLoginPanelLayout = new javax.swing.GroupLayout(stuffLoginPanel);
        stuffLoginPanel.setLayout(stuffLoginPanelLayout);
        stuffLoginPanelLayout.setHorizontalGroup(
            stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stuffLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stuffLebel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(stuffLoginPanelLayout.createSequentialGroup()
                .addGroup(stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(stuffLoginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(stuffLoginPanelLayout.createSequentialGroup()
                                .addComponent(stuffLebel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stuffLoginPanelLayout.createSequentialGroup()
                                .addComponent(stuffLebel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonN, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(logInButton)
                        .addGap(60, 60, 60))
                    .addGroup(stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(stuffLoginPanelLayout.createSequentialGroup()
                            .addGap(363, 363, 363)
                            .addComponent(loginLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(stuffLoginPanelLayout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stuffLoginPanelLayout.setVerticalGroup(
            stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stuffLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stuffLebel3)
                .addGap(32, 32, 32)
                .addGroup(stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stuffLebel1)
                    .addComponent(buttonN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stuffLoginPanelLayout.createSequentialGroup()
                        .addGroup(stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stuffLebel2)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stuffLoginPanelLayout.createSequentialGroup()
                        .addComponent(logInButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(stuffLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(476, 476, 476))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stuffLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(stuffLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(afterLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        String sn = "sudo";
        String sp = "uiu";
        String nameS = buttonN.getText();
        String passS = passField.getText();
        if(( nameS.equals(sn)) && (passS.equals(sp) ) ){
           // AfterLogin j = new AfterLogin();
           // j.setVisible(true);
            afterLogin.setVisible(true);
        }
        else
        {
            loginLable1.setText("invalid username or password");
           
            
        }
    }//GEN-LAST:event_logInButtonActionPerformed

    private void logInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInButtonMouseClicked
      
    }//GEN-LAST:event_logInButtonMouseClicked

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        HomePage h= new HomePage();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void seeOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeOrderListActionPerformed
        seeOrderList.setBackground(Color.red);
        try
        {
            BufferedReader wr = new BufferedReader( new FileReader("stuff.txt"));
            DefaultTableModel model= (DefaultTableModel) managementTable.getModel();
            String q;
            while( (q=wr.readLine())!=null)
            {
           String l[]=q.split(" ");
            
             model.addRow(new Object[]{l[0],l[1],l[2],l[3],l[4],l[5],l[6],l[7],l[8],l[9]});
            
            
            }
        }
        catch(Exception xx)
        {
            
        }
    }//GEN-LAST:event_seeOrderListActionPerformed

    private void serialCleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialCleanButtonActionPerformed
       serialCleanButton.setBackground(Color.red);
        try {
            BufferedWriter wr= new BufferedWriter( new FileWriter("serial.txt"));
            wr.flush();
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_serialCleanButtonActionPerformed

    private void orderCleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCleanButtonActionPerformed
       orderCleanButton.setBackground(Color.red);
        try {
            BufferedWriter wr= new BufferedWriter( new FileWriter("stuff.txt"));
            wr.flush();
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_orderCleanButtonActionPerformed

    private void wholeInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wholeInfoButtonActionPerformed
        wholeInfoButton.setBackground(Color.red);
        WholeInformation w= new WholeInformation();
        this.setVisible(false);
        w.setVisible(true);
    }//GEN-LAST:event_wholeInfoButtonActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel afterLogin;
    private javax.swing.JTextField buttonN;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logInButton;
    private javax.swing.JLabel loginLable1;
    private javax.swing.JTable managementTable;
    private javax.swing.JButton orderCleanButton;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton seeOrderList;
    private javax.swing.JButton serialCleanButton;
    private javax.swing.JLabel stuffLebel1;
    private javax.swing.JLabel stuffLebel2;
    private javax.swing.JLabel stuffLebel3;
    private javax.swing.JPanel stuffLoginPanel;
    private javax.swing.JButton wholeInfoButton;
    // End of variables declaration//GEN-END:variables
}
